# Generated by Django 4.2.24 on 2026-01-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("sunday", "Sunday"),
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        help_text="e.g., Class 10-A, HSC-Science", max_length=50
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("teacher", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("room", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "ordering": ["day", "start_time"],
            },
        ),
    ]
